### PR TITLE
fixes "warning: `<<' after local variable or literal is interpreted a…

### PR DESCRIPTION
**Pull request by griest024**
…s binary operator"
I'm not sure if this fixes anything functional but at least it removes the warning.

### CODE REVIEW

**Comment by byteit101** [comment]
While this may work, I'm actually trying to get rid of this repository. I've written a much cleaner fxmlloader implementation that is dependent upon jruby/jruby#3366 to fixed in jruby, and once that is done, this ugly code will be deleted. I'll pull this in however, as I'm not sure how soon that would be, and this was clearly bugging you enough to submit a PR.

**Comment by griest024** [comment]
Is there a repo for the new implementation or are you  committing it directly to jruby? And it was bugging me, I would rather not clutter up my terminal unnecessarily. I figure others feel the same way.

**Comment by byteit101** [comment]
No, I was going to commit it directly to jrubyfx. Right now without #3366 fix, it works on classes, but not custom controls. I suppose I could push it to a new branch, though this week I'm away from my main dev machine.

**Comment by griest024** [comment]
I'm in no hurry.

**Comment by byteit101** [comment]
Still not final on it, but I've pushed it to github for the moment: https://github.com/byteit101/JRubyFX-FXMLLoader/blob/newloader/lib/jrubyfx-fxmlloader2.rb (currently not integrated with anything yet)

**Comment by griest024** [comment]
Will you release a new version of jrubyfx when it is integrated? (1.2 or whatever)

**Comment by byteit101** [comment]
Likely to be 2.0, but yes, once jruby bugs are fixed

**Comment by griest024** [comment]
Okay i'll keep an eye out, thanks

**Pull request merged**
